[workspace]
name = "lbm-caiman-python"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64"]

[dependencies]
python = ">=3.12.7,<3.12.10"
caiman = "*"
pip = "*"

[pypi-dependencies]
lbm-caiman-python = { path = ".", editable = true }
mbo-utilities = ">=2.5.3"

[tasks]
test = "pytest"
lint = "ruff check lbm_caiman_python"
format = "ruff format lbm_caiman_python"
setup-caiman = "caimanmanager install"

[feature.dev.dependencies]
ruff = "*"
pytest = "*"

[feature.docs.pypi-dependencies]
docutils = ">=0.21.2"
myst-nb = ">=1.2.0"
sphinx = ">=8.1.3"
sphinx-autodoc2 = ">=0.5.0"
sphinx-copybutton = ">=0.5.2"
sphinx-togglebutton = "*"
sphinx-design = ">=0.6.1"
sphinxcontrib-bibtex = "*"
sphinx-tippy = "*"
sphinx-book-theme = "*"
numpydoc = "*"
ipykernel = "*"
sphinxcontrib-images = "*"
sphinxcontrib-video = "*"
jupytext = "*"

[feature.docs.tasks]
docs = "sphinx-build -b html docs docs/_build/html"

[environments]
default = { features = ["dev"], solve-group = "default" }
docs = { features = ["docs"], solve-group = "default" }
